version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
    environment:
      - XDEBUG_MODE=develop,debug # para o xdebug
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    extra_hosts:
      - "host.docker.internal:host-gateway" # para o xdebug
    ports:
      - "8000:80"
  db:
      image: mysql:5.7
      command: [mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all, --max-connections=1001]
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: querir
      ports:
        - "33066:3306"
      working_dir: /var/lib/mysql
      volumes:
      - /var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
       - "db"
      ports:
       - "8002:80"
      environment:
       - PMA_HOST=db
       - PMA_USER=root
       - PMA_PASSWORD=root
  redis:
    image: redis:6.2
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
    ports:
      - 8081:8081
    depends_on:
      - redis